// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdwyypdgmtoqcuxxgtnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkd3l5cGRnbXRvcWN1eHhndG5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTQ3MTUsImV4cCI6MjA3MjkzMDcxNX0.wZ5SjEvyN5j98GtLEnsJ3JPBlHpPD8VMOO6TfplmTzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});